name: macos

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        gem install bundler --no-document
        bundle install
    - name: Run test
      run: |
        rake spec
